services:
  - type: web
    name: urlsharpener
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: CORS_ALLOWED_ORIGINS
        value: https://url-sharpener.netlify.app
      - key: JDBC_URL
        sync: false
      - key: JDBC_USERNAME
        sync: false
      - key: JDBC_PASSWORD
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_SSL
        value: "true"
